# Generated by Django 5.0.6 on 2024-06-28 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='file',
        ),
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
    ]
