# Generated by Django 5.0.6 on 2024-06-28 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_student_file_remove_student_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
